apiVersion: batch/v1
kind: Job
metadata: 
     name: my-job 
    spec:
       schedule: "* * * * *" 
       completions: 10
       parallelism: 2
       activeDeadlineSecond: 20    
       template:
         metadata: 
        name: my-busybox     
            spec: 
              containers:
                - name: busybox 
                  image: busy box
                  command: ["echo","k8s JOBS"]
            restartPolicy: Never      
